import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import 'animate.css';
import ClientLayout from "@/Components/RootingClient";

// const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const pathname = usePathname();
  // const showNavbar = !pathname.startsWith('/auth');

  return (
    <html lang="en">
      <body className={`${poppins.className} bg-page`}>
        <ClientLayout>
          {children}
        </ClientLayout>
      </body>
    </html>
  );
}
